# Generated by Django 5.0.4 on 2024-05-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restock',
            name='new_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restock',
            name='old_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
