# Generated by Django 5.0.4 on 2024-05-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(blank=True, max_length=200, null=True)),
                ('is_borrowed_verified', models.BooleanField(default=False)),
                ('books', models.ManyToManyField(related_name='book_carts', to='book.book')),
            ],
            options={
                'db_table': 'book_cart',
            },
        ),
    ]
