# Generated by Django 5.0.4 on 2024-05-16 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcart',
            name='borrowed_verified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookcart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='bookcart',
            name='is_returned_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookcart',
            name='returned_verified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookcart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
