# Generated by Django 5.0.4 on 2024-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcart', '0002_bookcart_borrowed_verified_by_bookcart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcart',
            name='set_to_return',
            field=models.BooleanField(default=False),
        ),
    ]
