# Generated by Django 5.0.4 on 2024-05-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcart', '0003_bookcart_set_to_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcart',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned')], default='borrowed', max_length=10),
        ),
    ]
