# Generated by Django 5.0.4 on 2024-04-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
