# Generated by Django 5.0.4 on 2024-05-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
