# Generated by Django 5.0.4 on 2024-05-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
