# Generated by Django 5.0.4 on 2024-05-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
