# Generated by Django 5.0.4 on 2024-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_code', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'subject_subject',
            },
        ),
    ]
